language: node_js
node_js:
  - 15.11.0
script:
  - node index.js

deploy:
  provider: releases
  api_key: "**"
  file: .
  skip_cleanup: true
  on:
    tags: false
    branches:
      only:
        - main
