language: node_js
node_js:
  - 15.11.0
script:
  - node index.js

deploy:
  provider: releases
  api_key: "30a2cc85bde5155af70f7025a842cece40d65027"
  file: .
  skip_cleanup: true
  on:
    tags: false
    branches: 
      only:
        - deploy
